# Generated by Django 6.0.2 on 2026-04-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technology & Programming'), ('design', 'Design & Creative'), ('writing', 'Writing & Content'), ('tutoring', 'Tutoring & Academics'), ('music', 'Music & Arts'), ('language', 'Language & Translation'), ('fitness', 'Fitness & Wellness'), ('other', 'Other')], default='other', max_length=50)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('negotiable', 'Negotiable'), ('paid', 'Paid')], default='negotiable', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if free or negotiable', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technology & Programming'), ('design', 'Design & Creative'), ('writing', 'Writing & Content'), ('tutoring', 'Tutoring & Academics'), ('music', 'Music & Arts'), ('language', 'Language & Translation'), ('fitness', 'Fitness & Wellness'), ('other', 'Other')], default='other', max_length=50)),
                ('budget', models.CharField(blank=True, default='', help_text='e.g. Free, ₹500, Negotiable', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('skills_offered', models.TextField(blank=True, default='', help_text='Comma-separated list of skills')),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
