# Generated by Django 6.0.2 on 2026-04-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='servicepost',
            name='location',
            field=models.CharField(blank=True, help_text='Where is this service available?', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology & Programming'), ('design', 'Graphic Design & Creative'), ('writing', 'Writing & Translation'), ('languages', 'Languages & Tutoring'), ('business', 'Business & Marketing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('negotiable', 'Negotiable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology & Programming'), ('design', 'Graphic Design & Creative'), ('writing', 'Writing & Translation'), ('languages', 'Languages & Tutoring'), ('business', 'Business & Marketing'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skills.servicepost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
