# Generated by Django 6.0.2 on 2026-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_servicepost_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('coding', 'Coding'), ('teaching', 'Teaching'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('coding', 'Coding'), ('teaching', 'Teaching'), ('other', 'Other')], max_length=50),
        ),
    ]
