# Generated by Django 6.0.2 on 2026-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_servicepost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
