# Generated by Django 6.0.2 on 2026-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_servicepost_custom_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('coding', 'Coding'), ('teaching', 'Teaching'), ('marketing', 'Marketing'), ('photography', 'Photography'), ('video_editing', 'Video Editing'), ('writing', 'Writing'), ('tutoring', 'Tutoring'), ('home_services', 'Home Services'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('coding', 'Coding'), ('teaching', 'Teaching'), ('marketing', 'Marketing'), ('photography', 'Photography'), ('video_editing', 'Video Editing'), ('writing', 'Writing'), ('tutoring', 'Tutoring'), ('home_services', 'Home Services'), ('other', 'Other')], max_length=50),
        ),
    ]
