# Generated by Django 6.0.2 on 2026-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_servicepost_image_alter_servicepost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='delivery_time',
            field=models.CharField(choices=[('instant', 'Instant / Urgent'), ('24h', 'Within 24 Hours'), ('2-3d', '2-3 Business Days'), ('1w', 'Within 1 Week'), ('negotiable', 'Flexible / Negotiable')], default='negotiable', max_length=50),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='payment_methods',
            field=models.CharField(choices=[('upi', 'UPI / QR Code'), ('cash', 'Cash on Delivery'), ('gpay_phonepe', 'Google Pay / PhonePe'), ('bank_transfer', 'Bank Transfer'), ('negotiable', 'Negotiable / Other')], default='negotiable', max_length=50),
        ),
    ]
