# Generated by Django 6.0.2 on 2026-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_servicepost_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('graphic_design', 'Graphic Design'), ('video_editing', 'Video Editing'), ('writing', 'Content Writing'), ('tutoring', 'Tutoring'), ('assignment', 'Assignment Help'), ('presentation', 'Presentation Design'), ('resume', 'Resume Making'), ('exam_prep', 'Exam Preparation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('graphic_design', 'Graphic Design'), ('video_editing', 'Video Editing'), ('writing', 'Content Writing'), ('tutoring', 'Tutoring'), ('assignment', 'Assignment Help'), ('presentation', 'Presentation Design'), ('resume', 'Resume Making'), ('exam_prep', 'Exam Preparation'), ('other', 'Other')], max_length=50),
        ),
    ]
