# Generated by Django 6.0.2 on 2026-04-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_servicepost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='payment_methods',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('online', 'Online')], default='negotiable', max_length=50),
        ),
    ]
