# Generated by Django 6.0.2 on 2026-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_servicepost_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='payment_methods',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('online', 'Online'), ('negotiable', 'Flexible / Negotiable')], default='negotiable', max_length=50),
        ),
    ]
