# Generated by Django 6.0.2 on 2026-04-11 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_rename_content_message_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepost',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='price_type',
        ),
        migrations.AddField(
            model_name='servicepost',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('online', 'Online')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('negotiable', 'Negotiable')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bookings', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='skills.servicepost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
