# Generated by Django 6.0.2 on 2026-04-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_remove_servicepost_payment_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('negotiable', 'Negotiable')], max_length=20),
        ),
    ]
