# Generated by Django 6.0.2 on 2026-04-12 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepost',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameModel(
            old_name='ServiceRequest',
            new_name='HelpRequest',
        ),
        migrations.RenameField(
            model_name='helprequest',
            old_name='requester',
            new_name='user',
        ),
        migrations.RenameModel(
            old_name='ServiceBooking',
            new_name='Request',
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='skills.servicepost'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
