# Generated by Django 6.0.2 on 2026-04-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_remove_servicerequest_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='skills.payment'),
        ),
    ]
