# Generated by Django 6.0.2 on 2026-04-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_request_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
