# Generated by Django 6.0.2 on 2026-04-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0016_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
