# Generated by Django 6.0.2 on 2026-04-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_rename_servicepost_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='skills.request'),
        ),
        migrations.AlterField(
            model_name='message',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_messages', to='skills.service'),
        ),
    ]
