# Generated by Django 6.0.2 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0023_payment_request_request_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='simulator', help_text='Stripe, Razorpay, Simulator', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_file',
            field=models.FileField(blank=True, help_text='Added by provider', null=True, upload_to='deliveries/'),
        ),
        migrations.AddField(
            model_name='request',
            name='requirement_file',
            field=models.FileField(blank=True, help_text='Added by requester', null=True, upload_to='requirements/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
