# Generated by Django 6.0.2 on 2026-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0024_payment_gateway_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Video meeting link like Zoom/Meet', null=True),
        ),
    ]
