# Generated by Django 6.0.2 on 2026-04-14 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0025_request_meeting_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'service')},
        ),
    ]
