# Generated by Django 6.0.2 on 2026-04-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0027_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
