# Generated by Django 6.0.2 on 2026-05-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0028_service_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('Mysore', 'Mysore'), ('Bangalore', 'Bangalore'), ('Mangalore', 'Mangalore'), ('Chennai', 'Chennai'), ('Hyderabad', 'Hyderabad')], help_text='City where this service is available', max_length=100),
        ),
    ]
