# Generated by Django 6.0.2 on 2026-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0029_add_location_choices_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', help_text='Online or Offline delivery', max_length=20),
        ),
    ]
